name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the Attendance & Time Table App
title: '[FEATURE] '
labels: ['enhancement', 'active']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the details below.

        📋 **Before submitting**: 
        - Search existing issues to avoid duplicates
        - Check if this feature aligns with the project goals

  - type: textarea
    id: feature-description
    attributes:
      label: 🎯 Feature Description
      description: A clear and concise description of the feature you'd like to see implemented
      placeholder: 'I would like to see...'
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: 'Currently, users cannot...'
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: How would you like this feature to work?
      placeholder: 'The feature should work by...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: 'Alternative approaches could be...'
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Essential for functionality
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 📱 Platform
      description: Which platform(s) should this feature support?
      multiple: true
      options:
        - Android
        - iOS
        - Both
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
      placeholder: 'Additional details, mockups, or references...'
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Contribution
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am willing to help implement this feature if needed
          required: false
        - label: I understand that this feature request may take time to implement
          required: true
