name: Welcome New Issues

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Welcome new issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `👋 **Welcome to Attendance AI!**\n\nThank you for opening this issue. Here's what happens next:\n\n**For Contributors:**\n- 🎯 Comment \`/assign\` to assign this issue to yourself\n- 📚 Read our [Contributing Guidelines](.github/CONTRIBUTING.md)\n- 🔗 Check for issue dependencies mentioned in the description\n- ⚙️ Follow the [Setup Guide](.github/SETUP.md) to get started\n\n**For Maintainers:**\n- 🏷️ Please add appropriate labels\n- 🔍 Review for completeness and clarity\n- 🔄 Check for duplicates\n\n**Issue Assignment:**\n- Only issues with the \`active\` label can be assigned\n- Use \`/assign\` to self-assign\n- Use \`/unassign\` to unassign yourself\n\nHappy coding! 🚀`
            });

            // Add the active label to new issues
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['active']
              });
            } catch (error) {
              console.log('Active label may not exist yet, skipping auto-labeling');
            }
